disabled_rules: # rule identifiers to exclude from running
  - line_length
  - type_body_length
  - function_body_length

excluded: # paths to ignore during linting. overridden by `included`.
- Carthage
- Pods
